name: perceive_slidable
description: A widget that can be dragged and scrolled in a single gesture and snapped to a list of extents.
version: 0.1.0
homepage: https://github.com/bxqm/perceive_slidable

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tuple:
  fort: 0.1.2
  flutter_bloc: ^7.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: